name: Atividade 4

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'

jobs:
  exemplo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Script personalizado
        run: |
          echo "Início do script personalizado"
          echo "Data atual: $(date)"
          echo "Listando arquivos no diretório atual:"
          ls -la